[tool.poetry]
name = "carbon-acx"
version = "0.1.0"
description = "Carbon accounting framework"
authors = ["Example <example@example.com>"]
license = "MIT"
packages = [{include = "calc"}, {include = "app"}]

[tool.poetry.dependencies]
python = "^3.11"
pandas = "*"
pydantic = "^2.0"
plotly = "*"
dash = "*"
pyyaml = "*"
jinja2 = "*"

[tool.poetry.group.dev.dependencies]
pytest = "^7.0"
pytest-cov = "^4.0"
ruff = "^0.1.3"
black = "^23.7"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
line-length = 100

[tool.black]
line-length = 100
