name = "carbon-acx-compute"
main = "workers/compute/index.ts"
compatibility_date = "2024-05-01"

[vars]
ACX_DATASET_VERSION = "dev"

# Cloudflare Pages build configuration
pages_build_output_dir = "dist/site"

[dev]
port = 8787
