name = "carbon-acx-compute"
main = "workers/compute/index.ts"
compatibility_date = "2024-05-01"

[vars]
ACX_DATASET_VERSION = "dev"

routes = [
  { pattern = "/api/*", script = "compute" }
]

[dev]
port = 8787

[[d1_databases]]
binding = "DB"
database_name = "acx"
database_id = "00000000-0000-0000-0000-000000000000"
