name = "carbon-acx-compute"
main = "workers/compute/index.ts"
compatibility_date = "2024-05-01"

[vars]
ACX_DATASET_VERSION = "dev"

# Cloudflare Pages build configuration
# Build command: pnpm run build:web
# Output directory: apps/carbon-acx-web/dist
pages_build_output_dir = "apps/carbon-acx-web/dist"

[dev]
port = 8787
