name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Poetry
        run: pipx install poetry

      - name: Install deps
        run: poetry install --no-interaction --no-root

      - name: Lint
        run: |
          poetry run ruff check .
          poetry run black --check .

      - name: Test
        run: poetry run pytest --maxfail=1 --disable-warnings -q

      - name: Build derived outputs
        run: poetry run make build

      - name: Upload build outputs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-outputs
          path: calc/outputs
          if-no-files-found: warn
          retention-days: 7
