name: CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Poetry
        run: pip install poetry==1.7.1

      - name: Configure Poetry
        run: poetry config virtualenvs.create false

      - name: Install dependencies
        run: poetry install --with dev --extras db --no-root

      - name: Verify lockfile consistency
        run: poetry lock --check

      - name: Lint
        run: make lint

      - name: Test
        run: make test

      - name: Build packages
        run: make build site package

      - name: Upload SBOM
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: dist/sbom.cdx.json
          if-no-files-found: error

      - name: Vulnerability scan
        run: poetry run pip-audit --strict

      - name: Upload dist artifacts bundle
        uses: actions/upload-artifact@v4
        with:
          name: dist-artifacts
          path: dist/artifacts
          if-no-files-found: error

      - name: Upload static site bundle
        uses: actions/upload-artifact@v4
        with:
          name: dist-site
          path: dist/site
          if-no-files-found: error

  deploy-pages:
    needs: build
    if: github.ref == 'refs/heads/main'
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Download static site
        uses: actions/download-artifact@v4
        with:
          name: dist-site
          path: dist-site

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: dist-site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
