name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  lint-yaml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: .github/workflows
          config_file: .yamllint.yml

  build-static:
    runs-on: ubuntu-latest
    needs: [lint-yaml]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Poetry
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: "1.8.3"

      - name: Install deps
        run: poetry install --no-interaction --no-root

      - name: Build artifacts (CSV backend)
        env:
          ACX_GENERATED_AT: "1970-01-01T00:00:00+00:00"
          ACX_DATA_BACKEND: "csv"
          ACX_OUTPUT_ROOT: "dist/artifacts"
          PYTHONPATH: "."
        run: make build-static

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-artifacts
          path: dist/artifacts

  tests:
    runs-on: ubuntu-latest
    needs: [build-static]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - uses: abatilo/actions-poetry@v3
        with:
          poetry-version: "1.8.3"
      - run: poetry install --no-interaction
      - name: Run pytest
        run: poetry run pytest -q
