---
name: Fetch references

on:
  workflow_dispatch:
    inputs:
      only_ids:
        description: "Comma separated list of source_ids to fetch"
        required: false
        type: string
      domains_allowlist:
        description: "Optional newline separated domain patterns (e.g. *.gov)"
        required: false
        type: string
      normalize:
        description: "Run normalization after fetching"
        required: false
        default: "true"
        type: boolean

jobs:
  fetch:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Git LFS
        run: |
          git lfs install --local

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          set -euo pipefail
          pipx install poetry
          poetry install --with dev

      - name: Prepare CLI arguments
        run: |
          set -euo pipefail
          args=()

          if [[ -n "${{ inputs.only_ids }}" ]]; then
            args+=( "--only" "${{ inputs.only_ids }}" )
          fi

          if [[ -n "${{ inputs.domains_allowlist }}" ]]; then
            mkdir -p refs
            printf '%s\n' "${{ inputs.domains_allowlist }}" \
              > refs/domains_allowlist.txt
            args+=( "--domains" "refs/domains_allowlist.txt" )
          fi

          if [[ ${#args[@]} -gt 0 ]]; then
            printf 'ARGS=%s\n' "$(printf '%q ' "${args[@]}")" >> "$GITHUB_ENV"
          else
            echo 'ARGS=' >> "$GITHUB_ENV"
          fi

      - name: refs-check
        run: make refs-check

      - name: refs-fetch
        run: make refs-fetch

      - name: refs-normalize
        if: ${{ inputs.normalize == 'true' }}
        run: make refs-normalize

      - name: refs-audit
        run: make refs-audit

      - name: Persist fetched refs as artifact
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: fetched-references
          path: |
            refs/
            calc/references/data/
