---
name: Fetch references

on:
  workflow_dispatch:
    inputs:
      only_ids:
        description: "Comma separated list of source_ids to fetch"
        required: false
        type: string
      domains_allowlist:
        description: "Optional newline separated domain patterns (e.g. *.gov)"
        required: false
        type: string
      normalize:
        description: "Run normalization after fetching"
        required: false
        default: true
        type: boolean

jobs:
  fetch:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          pipx install poetry
          poetry install --with dev

      - name: Prepare args from inputs
        id: args
        run: |
          set -euo pipefail
          args=()

          # only_ids → --only-ids
          if [[ -n "${{ inputs.only_ids }}" ]]; then
            args+=( "--only-ids" "${{ inputs.only_ids }}" )
          fi

          # domains_allowlist → file, then --domains <file>
          if [[ -n "${{ inputs.domains_allowlist }}" ]]; then
            mkdir -p refs
            printf '%s\n' "${{ inputs.domains_allowlist }}" \
              > refs/domains_allowlist.txt
            args+=( "--domains" "refs/domains_allowlist.txt" )
          fi

          # normalize boolean (already boolean in YAML inputs)
          if [[ "${{ inputs.normalize }}" == "true" ]]; then
            args+=( "--normalize" )
          fi

          printf 'ARGS=%q ' "${args[@]}" | tee -a "$GITHUB_OUTPUT"
          echo

      - name: Fetch references
        run: |
          set -euo pipefail
          # Adjust path to your fetch script if different:
          # examples assume: calc/references/fetch_refs.py
          poetry run python calc/references/fetch_refs.py ${ARGS:-}

      - name: Persist fetched refs as artifact (optional)
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: fetched-references
          path: |
            refs/
            calc/references/data/
